# Loading and parsing of .aptww files (the per-player plando files generated by the Archipelago APWorld).
# Shared by the GUI and the command line.

from base64 import b64decode
import os
import re
import zipfile
from dataclasses import fields

from ruamel.yaml import YAML
yaml = YAML(typ="safe")

from options.wwrando_options import EntranceMixMode, KeyLunacyMode, Options, SwordMode, TrickDifficulty
from randomizer import Plando

class APTWWFileError(Exception):
  # The message is rich text (for display in the GUI). Use plain_text() when printing to a console.
  def plain_text(self) -> str:
    text = re.sub(r"\s*<br>\s*", "\n", str(self))
    text = re.sub(r"<[^>]+>", "", text)
    return text.strip()

def load_and_validate_ap_plando_file(plando_file: str) -> dict[str, dict]:
  if not os.access(plando_file, os.R_OK):
    raise APTWWFileError(
      """The APTWW file could not be opened.<br><br>
      Please ensure that the program has read permissions for the file and try again."""
    )

  try:
    with zipfile.ZipFile(plando_file, "r") as z:
      with z.open("plando") as plando_in_zip:
        plando_dict = yaml.load(b64decode(plando_in_zip.read()))
  except:
    try:
      with open(plando_file, "r") as f:
        plando_dict = yaml.load(f)
    except:
      plando_dict = None

  if not isinstance(plando_dict, dict):
    raise APTWWFileError(
      """There was an error trying to read the APTWW file.<br><br>
      Please ensure that the file has not been modified or corrupted and try again."""
    )

  # Check the APTWW version.
  error_msg = None
  if "Version" not in plando_dict:
    # Pre v2.5.0
    if "Name" in plando_dict:
      error_msg = """The APTWW file appears to have been generated on v2.4.0 of the APWorld.<br><br>
        You should use the 2.2.0 version of the randomizer build instead.<br>
        Download here: <a href=\"https://github.com/tanjo3/wwrando/releases/tag/ap_2.2.0\">https://github.com/tanjo3/wwrando/releases/tag/ap_2.2.0</a>"""
    else:
      test_location = plando_dict["Locations"]["Outset Island - Underneath Link's House"]
      if isinstance(test_location, dict):
        error_msg = """The APTWW file appears to have been generated on v2.3.x of the APWorld.<br><br>
          You should use the 2.1.0 version of the randomizer build instead.<br>
          Download here: <a href=\"https://github.com/tanjo3/wwrando/releases/tag/ap_2.1.0\">https://github.com/tanjo3/wwrando/releases/tag/ap_2.1.0</a>"""
      else:
        error_msg = """The APTWW file appears to have been generated on a pre-v2.3.0 of the APWorld.<br><br>
          You should use the 2.0.0 version of the randomizer build instead.<br>
          Download here: <a href=\"https://github.com/tanjo3/wwrando/releases/tag/ap_2.0.0\">https://github.com/tanjo3/wwrando/releases/tag/ap_2.0.0</a>"""
  else:
    major, minor, patch = plando_dict["Version"]
    if major == 2 and minor == 6:
      error_msg = """The APTWW file appears to have been generated on v%d.%d.%d of the APWorld.<br><br>
        You should use the 2.4.0 version of the randomizer build instead.<br>
        Download here: <a href=\"https://github.com/tanjo3/wwrando/releases/tag/ap_2.4.0\">https://github.com/tanjo3/wwrando/releases/tag/ap_2.4.0</a>""" % (major, minor, patch)
    elif major == 2 and minor == 5:
      error_msg = """The APTWW file appears to have been generated on v%d.%d.%d of the APWorld.<br><br>
        You should use the 2.3.0 version of the randomizer build instead.<br>
        Download here: <a href=\"https://github.com/tanjo3/wwrando/releases/tag/ap_2.3.0\">https://github.com/tanjo3/wwrando/releases/tag/ap_2.3.0</a>""" % (major, minor, patch)

  if error_msg:
    error_msg += """<br><br>
    However, The Wind Waker is now officially supported in Archipelago. Consider updating Archipelago and regenerating your multiworld."""
    raise APTWWFileError(error_msg)
  else:
    return plando_dict

def read_ap_plando_file(plando_file: str, options: Options) -> Plando:
  """Loads an .aptww file, overwrites the given options with the ones it specifies, and returns its plando."""
  plando_file = load_and_validate_ap_plando_file(plando_file)

  # Set options dataclass from the plando file
  for field in fields(options):
    if field.name in plando_file["Options"]:
      value = plando_file["Options"][field.name]

      if field.type is int:
        setattr(options, field.name, value)
      elif field.type is bool:
        setattr(options, field.name, bool(value))
      elif field.type is SwordMode:
        match value:
          case 0: setattr(options, field.name, SwordMode.START_WITH_SWORD)
          case 1: setattr(options, field.name, SwordMode.NO_STARTING_SWORD)
          case 2: setattr(options, field.name, SwordMode.SWORDS_OPTIONAL)
          case 3: setattr(options, field.name, SwordMode.SWORDLESS)
      elif field.type is EntranceMixMode:
          match value:
            case 0: setattr(options, field.name, EntranceMixMode.SEPARATE_DUNGEONS)
            case 1: setattr(options, field.name, EntranceMixMode.MIX_DUNGEONS)
      elif field.type is TrickDifficulty:
          match value:
            case 0: setattr(options, field.name, TrickDifficulty.NONE)
            case 1: setattr(options, field.name, TrickDifficulty.NORMAL)
            case 2: setattr(options, field.name, TrickDifficulty.HARD)
            case 3: setattr(options, field.name, TrickDifficulty.VERY_HARD)
      elif field.type is KeyLunacyMode:
          match value:
            case 0: setattr(options, field.name, KeyLunacyMode.START_WITH)
            case 1: setattr(options, field.name, KeyLunacyMode.VANILLA)
            case 2: setattr(options, field.name, KeyLunacyMode.DUNGEON)
            case 3: setattr(options, field.name, KeyLunacyMode.ANY_DUNGEON)
            case 4: setattr(options, field.name, KeyLunacyMode.LOCAL)
            case 5: setattr(options, field.name, KeyLunacyMode.KEYLUNACY)
      else:
        print(f"Bad option: {field.name} = {value}")
    else:
      if field.name in ["randomized_gear", "starting_gear"]:
        setattr(options, field.name, field.default_factory())
      if getattr(options, field.name) is None:
        setattr(options, field.name, field.default)

  # Item names from other games can contain characters the message font can't encode.
  for item_info in plando_file["Locations"].values():
    if item_info["game"] != "The Wind Waker":
      item_info["name"] = item_info["name"].encode("cp1252", "replace").decode("latin-1")

  # Save the rest of the plando in a dataclass
  return Plando(
    f"AP_{plando_file['Seed']}_P{plando_file['Slot']}",
    plando_file["Slot"],
    plando_file["Name"],
    plando_file["Required Bosses"],
    plando_file["Locations"],
    plando_file["Entrances"],
    plando_file["Charts"]
  )
