# Static per-location data for the in-game tracker.
#
# The detection columns (type, stage ID, bit, address) are ported from the Archipelago
# Wind Waker world, worlds/tww/Locations.py (LOCATION_TABLE), which is MIT licensed:
#   Copyright (c) 2017 LLCoolDave, Copyright (c) 2022 CaitSith2, Copyright (c) 2025 Berserker66
#   and the Archipelago contributors. https://github.com/ArchipelagoMW/Archipelago
# They keep that file's exact semantics, which are implemented by worlds/tww/TWWClient.py and
# resolved to byte addresses in tracker/locations.py.
#
# Locations that the randomizer's logic knows about but the APWorld comments out reuse the
# commented-out APWorld data where it has any (Kane's gate rewards). The rest have no known flag
# and use NONE, so they can only be marked manually. All of them are "Consumables only" or "No
# progression", so they never show up in a tracker built from progress locations anyway.
#
# Display names are short ASCII forms (at most 28 characters) of the part after the zone name,
# for the in-game location list.

from enum import Enum
from typing import NamedTuple


class LocationType(Enum):
  NONE = 0  # No known flag. Manual marking only.
  CHART = 1  # Sunken treasure. Salvage bit in the 64-bit big-endian field at 0x803C4CFC.
  BOCTO = 2  # Big Octo / gunboat. Bit of the big-endian u16 at address.
  CHEST = 3  # Chest-opened bit of the stage's saved info (u32 at +0x00).
  SWTCH = 4  # Switch bit of the stage's saved info (80-bit big-endian field at +0x04).
  PCKUP = 5  # Pickup bit of the stage's saved info (u32 at +0x14).
  EVENT = 6  # Bit of the event byte at address.
  SPECL = 7  # Special case. See SPECIAL_CHECKS in tracker/locations.py.


NONE = LocationType.NONE
CHART = LocationType.CHART
BOCTO = LocationType.BOCTO
CHEST = LocationType.CHEST
SWTCH = LocationType.SWTCH
PCKUP = LocationType.PCKUP
EVENT = LocationType.EVENT
SPECL = LocationType.SPECL


class LocationData(NamedTuple):
  display_name: str
  type: LocationType
  stage_id: int
  bit: int
  address: int | None = None


# Keyed by location name, in logic/item_locations.txt order.
# For CHART locations, the bit is the salvage bit of the island's vanilla chart. With randomized
# charts the bit moves with the chart, see tracker/locations.py.
LOCATION_DATA: dict[str, LocationData] = {
  "Outset Island - Underneath Link's House": LocationData("Underneath Link's House", CHEST, 0xB, 5),
  "Outset Island - Mesa the Grasscutter's House": LocationData("Mesa the Grasscutter's House", CHEST, 0xB, 4),
  "Outset Island - Orca - Give 10 Knight's Crests": LocationData("Orca - 10 Knight's Crests", EVENT, 0xB, 5, 0x803C5237),
  "Outset Island - Orca - Hit 500 Times": LocationData("Orca - Hit 500 Times", NONE, 0x0, 0),
  "Outset Island - Great Fairy": LocationData("Great Fairy", EVENT, 0xC, 4, 0x803C525C),
  "Outset Island - Jabun's Cave": LocationData("Jabun's Cave", CHEST, 0xB, 6),
  "Outset Island - Dig up Black Soil": LocationData("Dig up Black Soil", PCKUP, 0x0, 2),
  "Outset Island - Savage Labyrinth - Floor 30": LocationData("Savage Labyrinth - Floor 30", CHEST, 0xD, 11),
  "Outset Island - Savage Labyrinth - Floor 50": LocationData("Savage Labyrinth - Floor 50", CHEST, 0xD, 12),
  "Windfall Island - Jail - Tingle - First Gift": LocationData("Jail - Tingle - First Gift", SWTCH, 0xB, 53),
  "Windfall Island - Jail - Tingle - Second Gift": LocationData("Jail - Tingle - Second Gift", SWTCH, 0xB, 54),
  "Windfall Island - Jail - Maze Chest": LocationData("Jail - Maze Chest", CHEST, 0xB, 0),
  "Windfall Island - Chu Jelly Juice Shop - Give 15 Green Chu Jelly": LocationData("Chu Shop - 15 Green Jelly", EVENT, 0xB, 2, 0x803C5239),
  "Windfall Island - Chu Jelly Juice Shop - Give 15 Blue Chu Jelly": LocationData("Chu Shop - 15 Blue Jelly", EVENT, 0xB, 1, 0x803C5239),
  "Windfall Island - Ivan - Catch Killer Bees": LocationData("Ivan - Catch Killer Bees", EVENT, 0x0, 6, 0x803C523F),
  "Windfall Island - Mrs. Marie - Catch Killer Bees": LocationData("Mrs. Marie - Killer Bees", EVENT, 0xB, 7, 0x803C524B),
  "Windfall Island - Mrs. Marie - Give 1 Joy Pendant": LocationData("Mrs. Marie - 1 Joy Pendant", EVENT, 0xB, 0, 0x803C52EC),
  "Windfall Island - Mrs. Marie - Give 21 Joy Pendants": LocationData("Mrs. Marie - 21 Joy Pendants", EVENT, 0xB, 3, 0x803C5248),
  "Windfall Island - Mrs. Marie - Give 40 Joy Pendants": LocationData("Mrs. Marie - 40 Joy Pendants", EVENT, 0xB, 2, 0x803C5248),
  "Windfall Island - Lenzo's House - Left Chest": LocationData("Lenzo's House - Left Chest", CHEST, 0xB, 1),
  "Windfall Island - Lenzo's House - Right Chest": LocationData("Lenzo's House - Right Chest", CHEST, 0xB, 2),
  "Windfall Island - Lenzo's House - Become Lenzo's Assistant": LocationData("Lenzo - Become Assistant", SPECL, 0xB, 0, 0x803C52F0),
  "Windfall Island - Lenzo's House - Bring Forest Firefly": LocationData("Lenzo - Forest Firefly", EVENT, 0xB, 5, 0x803C5295),
  "Windfall Island - House of Wealth Chest": LocationData("House of Wealth Chest", CHEST, 0xB, 3),
  "Windfall Island - Maggie's Father - Give 20 Skull Necklaces": LocationData("Maggie's Dad - 20 Necklaces", EVENT, 0xB, 4, 0x803C52F1),
  "Windfall Island - Maggie - Free Item": LocationData("Maggie - Free Item", EVENT, 0xB, 0, 0x803C5296),
  "Windfall Island - Maggie - Delivery Reward": LocationData("Maggie - Delivery Reward", SPECL, 0xB, 0),
  "Windfall Island - Cafe Bar - Postman": LocationData("Cafe Bar - Postman", EVENT, 0xB, 1, 0x803C5296),
  "Windfall Island - Kreeb - Light Up Lighthouse": LocationData("Kreeb - Light Up Lighthouse", EVENT, 0x0, 5, 0x803C5247),
  "Windfall Island - Transparent Chest": LocationData("Transparent Chest", CHEST, 0x0, 10),
  "Windfall Island - Tott - Teach Rhythm": LocationData("Tott - Teach Rhythm", EVENT, 0x0, 6, 0x803C5238),
  "Windfall Island - Pirate Ship": LocationData("Pirate Ship", CHEST, 0xD, 5),
  "Windfall Island - 5 Rupee Auction": LocationData("5 Rupee Auction", EVENT, 0xB, 7, 0x803C523C),
  "Windfall Island - 40 Rupee Auction": LocationData("40 Rupee Auction", EVENT, 0xB, 0, 0x803C523B),
  "Windfall Island - 60 Rupee Auction": LocationData("60 Rupee Auction", EVENT, 0xB, 6, 0x803C523C),
  "Windfall Island - 80 Rupee Auction": LocationData("80 Rupee Auction", EVENT, 0xB, 5, 0x803C523C),
  "Windfall Island - Zunari - Stock Exotic Flower in Zunari's Shop": LocationData("Zunari - Exotic Flower", EVENT, 0x0, 6, 0x803C5295),
  "Windfall Island - Sam - Decorate the Town": LocationData("Sam - Decorate the Town", EVENT, 0x0, 4, 0x803C5247),
  "Windfall Island - Kane - Place Shop Guru Statue on Gate": LocationData("Kane - Shop Guru Statue", EVENT, 0x0, 4, 0x803C5250),
  "Windfall Island - Kane - Place Postman Statue on Gate": LocationData("Kane - Postman Statue", EVENT, 0x0, 3, 0x803C5250),
  "Windfall Island - Kane - Place Six Flags on Gate": LocationData("Kane - Six Flags", EVENT, 0x0, 2, 0x803C5250),
  "Windfall Island - Kane - Place Six Idols on Gate": LocationData("Kane - Six Idols", EVENT, 0x0, 1, 0x803C5250),
  "Windfall Island - Mila - Follow the Thief": LocationData("Mila - Follow the Thief", EVENT, 0x0, 3, 0x803C523A),
  "Windfall Island - Battlesquid - First Prize": LocationData("Battlesquid - First Prize", EVENT, 0xB, 0, 0x803C532A),
  "Windfall Island - Battlesquid - Second Prize": LocationData("Battlesquid - Second Prize", EVENT, 0xB, 1, 0x803C532A),
  "Windfall Island - Battlesquid - Under 20 Shots Prize": LocationData("Battlesquid - Under 20 Shots", EVENT, 0xB, 0, 0x803C532B),
  "Windfall Island - Pompie and Vera - Secret Meeting Photo": LocationData("Secret Meeting Photo", EVENT, 0x0, 2, 0x803C5295),
  "Windfall Island - Kamo - Full Moon Photo": LocationData("Kamo - Full Moon Photo", EVENT, 0x0, 4, 0x803C5295),
  "Windfall Island - Minenco - Miss Windfall Photo": LocationData("Minenco - Miss Windfall", EVENT, 0x0, 3, 0x803C5295),
  "Windfall Island - Linda and Anton": LocationData("Linda and Anton", EVENT, 0xB, 7, 0x803C524E),
  "Dragon Roost Island - Wind Shrine": LocationData("Wind Shrine", EVENT, 0x0, 3, 0x803C5253),
  "Dragon Roost Island - Rito Aerie - Give Hoskit 20 Golden Feathers": LocationData("Hoskit - 20 Golden Feathers", EVENT, 0xB, 7, 0x803C524D),
  "Dragon Roost Island - Chest on Top of Boulder": LocationData("Chest on Top of Boulder", CHEST, 0x0, 8),
  "Dragon Roost Island - Fly Across Platforms Around Island": LocationData("Fly Across Platforms", CHEST, 0x0, 9),
  "Dragon Roost Island - Rito Aerie - Mail Sorting": LocationData("Rito Aerie - Mail Sorting", EVENT, 0xB, 0, 0x803C5253),
  "Dragon Roost Island - Secret Cave": LocationData("Secret Cave", CHEST, 0xD, 0),
  "Dragon Roost Cavern - First Room": LocationData("First Room", CHEST, 0x3, 0),
  "Dragon Roost Cavern - Alcove With Water Jugs": LocationData("Alcove With Water Jugs", CHEST, 0x3, 2),
  "Dragon Roost Cavern - Water Jug on Upper Shelf": LocationData("Water Jug on Upper Shelf", PCKUP, 0x3, 1),
  "Dragon Roost Cavern - Boarded Up Chest": LocationData("Boarded Up Chest", CHEST, 0x3, 1),
  "Dragon Roost Cavern - Chest Across Lava Pit": LocationData("Chest Across Lava Pit", CHEST, 0x3, 13),
  "Dragon Roost Cavern - Rat Room": LocationData("Rat Room", CHEST, 0x3, 14),
  "Dragon Roost Cavern - Rat Room Boarded Up Chest": LocationData("Rat Room Boarded Up Chest", CHEST, 0x3, 3),
  "Dragon Roost Cavern - Bird's Nest": LocationData("Bird's Nest", PCKUP, 0x3, 3),
  "Dragon Roost Cavern - Dark Room": LocationData("Dark Room", CHEST, 0x3, 4),
  "Dragon Roost Cavern - Tingle Chest in Hub Room": LocationData("Tingle Chest in Hub Room", CHEST, 0x3, 16),
  "Dragon Roost Cavern - Pot on Upper Shelf in Pot Room": LocationData("Pot on Upper Shelf", PCKUP, 0x3, 0),
  "Dragon Roost Cavern - Pot Room Chest": LocationData("Pot Room Chest", CHEST, 0x3, 6),
  "Dragon Roost Cavern - Miniboss": LocationData("Miniboss", CHEST, 0x3, 17),
  "Dragon Roost Cavern - Under Rope Bridge": LocationData("Under Rope Bridge", CHEST, 0x3, 7),
  "Dragon Roost Cavern - Tingle Statue Chest": LocationData("Tingle Statue Chest", CHEST, 0x3, 15),
  "Dragon Roost Cavern - Big Key Chest": LocationData("Big Key Chest", CHEST, 0x3, 12),
  "Dragon Roost Cavern - Boss Stairs Right Chest": LocationData("Boss Stairs Right Chest", CHEST, 0x3, 11),
  "Dragon Roost Cavern - Boss Stairs Left Chest": LocationData("Boss Stairs Left Chest", CHEST, 0x3, 10),
  "Dragon Roost Cavern - Boss Stairs Right Pot": LocationData("Boss Stairs Right Pot", PCKUP, 0x3, 6),
  "Dragon Roost Cavern - Gohma Heart Container": LocationData("Gohma Heart Container", PCKUP, 0x3, 21),
  "Forest Haven - On Tree Branch": LocationData("On Tree Branch", PCKUP, 0xB, 2),
  "Forest Haven - Small Island Chest": LocationData("Small Island Chest", CHEST, 0x0, 7),
  "Forbidden Woods - First Room": LocationData("First Room", CHEST, 0x4, 0),
  "Forbidden Woods - Inside Hollow Tree's Mouth": LocationData("Inside Hollow Tree's Mouth", CHEST, 0x4, 1),
  "Forbidden Woods - Climb to Top Using Boko Baba Bulbs": LocationData("Climb Boko Baba Bulbs", CHEST, 0x4, 2),
  "Forbidden Woods - Pot High Above Hollow Tree": LocationData("Pot High Above Hollow Tree", PCKUP, 0x4, 1),
  "Forbidden Woods - Hole in Tree": LocationData("Hole in Tree", CHEST, 0x4, 6),
  "Forbidden Woods - Morth Pit": LocationData("Morth Pit", CHEST, 0x4, 8),
  "Forbidden Woods - Vine Maze Left Chest": LocationData("Vine Maze Left Chest", CHEST, 0x4, 7),
  "Forbidden Woods - Vine Maze Right Chest": LocationData("Vine Maze Right Chest", CHEST, 0x4, 5),
  "Forbidden Woods - Highest Pot in Vine Maze": LocationData("Highest Pot in Vine Maze", PCKUP, 0x4, 22),
  "Forbidden Woods - Tall Room Before Miniboss": LocationData("Tall Room Before Miniboss", CHEST, 0x4, 12),
  "Forbidden Woods - Mothula Miniboss Room": LocationData("Mothula Miniboss Room", CHEST, 0x4, 10),
  "Forbidden Woods - Past Seeds Hanging by Vines": LocationData("Past Seeds Hanging by Vines", CHEST, 0x4, 3),
  "Forbidden Woods - Chest Across Red Hanging Flower": LocationData("Across Red Hanging Flower", CHEST, 0x4, 11),
  "Forbidden Woods - Tingle Statue Chest": LocationData("Tingle Statue Chest", CHEST, 0x4, 15),
  "Forbidden Woods - Chest in Locked Tree Trunk": LocationData("Chest in Locked Tree Trunk", CHEST, 0x4, 9),
  "Forbidden Woods - Big Key Chest": LocationData("Big Key Chest", CHEST, 0x4, 4),
  "Forbidden Woods - Double Mothula Room": LocationData("Double Mothula Room", CHEST, 0x4, 14),
  "Forbidden Woods - Kalle Demos Heart Container": LocationData("Kalle Demos Heart Container", PCKUP, 0x4, 21),
  "Greatfish Isle - Hidden Chest": LocationData("Hidden Chest", CHEST, 0x0, 6),
  "Tower of the Gods - Chest Behind Bombable Walls": LocationData("Chest Behind Bombable Walls", CHEST, 0x5, 2),
  "Tower of the Gods - Pot Behind Bombable Walls": LocationData("Pot Behind Bombable Walls", PCKUP, 0x5, 0),
  "Tower of the Gods - Hop Across Floating Boxes": LocationData("Hop Across Floating Boxes", CHEST, 0x5, 1),
  "Tower of the Gods - Light Two Torches": LocationData("Light Two Torches", CHEST, 0x5, 10),
  "Tower of the Gods - Skulls Room Chest": LocationData("Skulls Room Chest", CHEST, 0x5, 3),
  "Tower of the Gods - Shoot Eye Above Skulls Room Chest": LocationData("Shoot Eye Above Skulls Room", CHEST, 0x5, 9),
  "Tower of the Gods - Tingle Statue Chest": LocationData("Tingle Statue Chest", CHEST, 0x5, 15),
  "Tower of the Gods - First Chest Guarded by Armos Knights": LocationData("Armos Knights - First Chest", CHEST, 0x5, 6),
  "Tower of the Gods - Stone Tablet": LocationData("Stone Tablet", EVENT, 0x5, 4, 0x803C5251),
  "Tower of the Gods - Darknut Miniboss Room": LocationData("Darknut Miniboss Room", CHEST, 0x5, 5),
  "Tower of the Gods - Second Chest Guarded by Armos Knights": LocationData("Armos Knights - Second Chest", CHEST, 0x5, 8),
  "Tower of the Gods - Floating Platforms Room": LocationData("Floating Platforms Room", CHEST, 0x5, 4),
  "Tower of the Gods - Top of Floating Platforms Room": LocationData("Top of Floating Platforms", CHEST, 0x5, 11),
  "Tower of the Gods - Eastern Pot in Big Key Chest Room": LocationData("E Pot in Big Key Chest Room", PCKUP, 0x5, 1),
  "Tower of the Gods - Big Key Chest": LocationData("Big Key Chest", CHEST, 0x5, 0),
  "Tower of the Gods - Gohdan Heart Container": LocationData("Gohdan Heart Container", PCKUP, 0x5, 21),
  "Hyrule - Master Sword Chamber": LocationData("Master Sword Chamber", CHEST, 0x9, 0),
  "Forsaken Fortress - Phantom Ganon": LocationData("Phantom Ganon", CHEST, 0x0, 16),
  "Forsaken Fortress - Chest Outside Upper Jail Cell": LocationData("Outside Upper Jail Cell", CHEST, 0x2, 0),
  "Forsaken Fortress - Chest Inside Lower Jail Cell": LocationData("Chest Inside Lower Jail Cell", CHEST, 0x2, 3),
  "Forsaken Fortress - Chest Guarded By Bokoblin": LocationData("Chest Guarded By Bokoblin", CHEST, 0x2, 2),
  "Forsaken Fortress - Chest on Bed": LocationData("Chest on Bed", CHEST, 0x2, 1),
  "Forsaken Fortress - Helmaroc King Heart Container": LocationData("Helmaroc Heart Container", PCKUP, 0x2, 21),
  "Mother and Child Isles - Inside Mother Isle": LocationData("Inside Mother Isle", CHEST, 0x0, 28),
  "Fire Mountain - Cave - Chest": LocationData("Cave - Chest", CHEST, 0xC, 0),
  "Fire Mountain - Lookout Platform Chest": LocationData("Lookout Platform Chest", CHEST, 0x1, 1),
  "Fire Mountain - Lookout Platform - Destroy the Cannons": LocationData("Lookout - Cannons", CHEST, 0x1, 0),
  "Fire Mountain - Big Octo": LocationData("Big Octo", BOCTO, 0x0, 0, 0x803C51F0),
  "Ice Ring Isle - Frozen Chest": LocationData("Frozen Chest", CHEST, 0x0, 18),
  "Ice Ring Isle - Cave - Chest": LocationData("Cave - Chest", CHEST, 0xC, 1),
  "Ice Ring Isle - Inner Cave - Chest": LocationData("Inner Cave - Chest", CHEST, 0xC, 21),
  "Headstone Island - Top of the Island": LocationData("Top of the Island", PCKUP, 0x0, 8),
  "Headstone Island - Submarine": LocationData("Submarine", CHEST, 0xA, 4),
  "Earth Temple - Transparent Chest In Warp Pot Room": LocationData("Warp Pot Room - Transparent", CHEST, 0x6, 0),
  "Earth Temple - Behind Curtain In Warp Pot Room": LocationData("Warp Pot Room - Curtain", PCKUP, 0x6, 0),
  "Earth Temple - Transparent Chest in First Crypt": LocationData("First Crypt - Transparent", CHEST, 0x6, 1),
  "Earth Temple - Chest Behind Destructible Walls": LocationData("Behind Destructible Walls", CHEST, 0x6, 12),
  "Earth Temple - Chest In Three Blocks Room": LocationData("Chest In Three Blocks Room", CHEST, 0x6, 2),
  "Earth Temple - Chest Behind Statues": LocationData("Chest Behind Statues", CHEST, 0x6, 3),
  "Earth Temple - Casket in Second Crypt": LocationData("Casket in Second Crypt", PCKUP, 0x6, 14),
  "Earth Temple - Stalfos Miniboss Room": LocationData("Stalfos Miniboss Room", CHEST, 0x6, 7),
  "Earth Temple - Tingle Statue Chest": LocationData("Tingle Statue Chest", CHEST, 0x6, 15),
  "Earth Temple - End of Foggy Room With Floormasters": LocationData("Foggy Room - End", CHEST, 0x6, 4),
  "Earth Temple - Kill All Floormasters in Foggy Room": LocationData("Foggy Room - Floormasters", CHEST, 0x6, 11),
  "Earth Temple - Behind Curtain Next to Hammer Button": LocationData("Curtain by Hammer Button", PCKUP, 0x6, 1),
  "Earth Temple - Chest in Third Crypt": LocationData("Chest in Third Crypt", CHEST, 0x6, 5),
  "Earth Temple - Many Mirrors Room Right Chest": LocationData("Many Mirrors - Right Chest", CHEST, 0x6, 9),
  "Earth Temple - Many Mirrors Room Left Chest": LocationData("Many Mirrors Room Left Chest", CHEST, 0x6, 10),
  "Earth Temple - Stalfos Crypt Room": LocationData("Stalfos Crypt Room", CHEST, 0x6, 14),
  "Earth Temple - Big Key Chest": LocationData("Big Key Chest", CHEST, 0x6, 6),
  "Earth Temple - Jalhalla Heart Container": LocationData("Jalhalla Heart Container", PCKUP, 0x6, 21),
  "Wind Temple - Chest Between Two Dirt Patches": LocationData("Between Two Dirt Patches", CHEST, 0x7, 0),
  "Wind Temple - Behind Stone Head in Hidden Upper Room": LocationData("Stone Head - Hidden Room", PCKUP, 0x7, 0),
  "Wind Temple - Tingle Statue Chest": LocationData("Tingle Statue Chest", CHEST, 0x7, 15),
  "Wind Temple - Chest Behind Stone Head": LocationData("Chest Behind Stone Head", CHEST, 0x7, 3),
  "Wind Temple - Chest in Left Alcove": LocationData("Chest in Left Alcove", CHEST, 0x7, 7),
  "Wind Temple - Big Key Chest": LocationData("Big Key Chest", CHEST, 0x7, 8),
  "Wind Temple - Chest In Many Cyclones Room": LocationData("Chest In Many Cyclones Room", CHEST, 0x7, 11),
  "Wind Temple - Behind Stone Head in Many Cyclones Room": LocationData("Stone Head - Cyclones Room", PCKUP, 0x7, 1),
  "Wind Temple - Chest In Middle Of Hub Room": LocationData("Chest In Middle Of Hub Room", CHEST, 0x7, 13),
  "Wind Temple - Spike Wall Room - First Chest": LocationData("Spike Wall - First Chest", CHEST, 0x7, 9),
  "Wind Temple - Spike Wall Room - Destroy All Cracked Floors": LocationData("Spike Wall - Cracked Floors", CHEST, 0x7, 10),
  "Wind Temple - Wizzrobe Miniboss Room": LocationData("Wizzrobe Miniboss Room", CHEST, 0x7, 5),
  "Wind Temple - Chest at Top of Hub Room": LocationData("Chest at Top of Hub Room", CHEST, 0x7, 2),
  "Wind Temple - Chest Behind Seven Armos": LocationData("Chest Behind Seven Armos", CHEST, 0x7, 4),
  "Wind Temple - Kill All Enemies in Tall Basement Room": LocationData("Tall Basement - Enemies", CHEST, 0x7, 12),
  "Wind Temple - Molgera Heart Container": LocationData("Molgera Heart Container", PCKUP, 0x7, 21),
  "Ganon's Tower - Maze Chest": LocationData("Maze Chest", CHEST, 0x8, 0),
  "Mailbox - Letter from Hoskit's Girlfriend": LocationData("Letter from Hoskit's GF", SPECL, 0x0, 0, 0x803C52DA),
  "Mailbox - Letter from Baito's Mother": LocationData("Letter from Baito's Mother", SPECL, 0x0, 0, 0x803C52D8),
  "Mailbox - Letter from Baito": LocationData("Letter from Baito", EVENT, 0x0, 0, 0x803C52A8),
  "Mailbox - Letter from Komali's Father": LocationData("Letter from Komali's Father", EVENT, 0x0, 0, 0x803C52E1),
  "Mailbox - Letter Advertising Bombs in Beedle's Shop": LocationData("Letter Advertising Bombs", EVENT, 0x0, 0, 0x803C52A9),
  "Mailbox - Letter Advertising Rock Spire Shop Ship": LocationData("Letter Advertising Shop Ship", EVENT, 0x0, 0, 0x803C52A6),
  "Mailbox - Beedle's Silver Membership Reward": LocationData("Beedle Silver Membership", NONE, 0x0, 0),
  "Mailbox - Beedle's Gold Membership Reward": LocationData("Beedle Gold Membership", NONE, 0x0, 0),
  "Mailbox - Letter from Orca": LocationData("Letter from Orca", EVENT, 0x0, 0, 0x803C52A7),
  "Mailbox - Letter from Grandma": LocationData("Letter from Grandma", SPECL, 0x0, 0, 0x803C52C9),
  "Mailbox - Letter from Aryll": LocationData("Letter from Aryll", EVENT, 0x0, 0, 0x803C52B7),
  "Mailbox - Letter from Tingle": LocationData("Letter from Tingle", EVENT, 0x0, 0, 0x803C52DE),
  "The Great Sea - Beedle's Shop Ship - 20 Rupee Item": LocationData("Beedle's Shop - 20 Rupees", EVENT, 0xA, 1, 0x803C5295),
  "The Great Sea - Salvage Corp Gift": LocationData("Salvage Corp Gift", EVENT, 0x0, 7, 0x803C5295),
  "The Great Sea - Cyclos": LocationData("Cyclos", EVENT, 0x0, 4, 0x803C5253),
  "The Great Sea - Goron Trading Reward": LocationData("Goron Trading Reward", EVENT, 0x0, 2, 0x803C526A),
  "The Great Sea - Withered Trees": LocationData("Withered Trees", EVENT, 0x0, 5, 0x803C525A),
  "The Great Sea - Ghost Ship": LocationData("Ghost Ship", CHEST, 0xA, 23),
  "Private Oasis - Chest at Top of Waterfall": LocationData("Chest at Top of Waterfall", CHEST, 0x0, 19),
  "Private Oasis - Cabana Labyrinth - Lower Floor Chest": LocationData("Cabana - Lower Floor Chest", CHEST, 0xC, 22),
  "Private Oasis - Cabana Labyrinth - Upper Floor Chest": LocationData("Cabana - Upper Floor Chest", CHEST, 0xC, 17),
  "Private Oasis - Big Octo": LocationData("Big Octo", BOCTO, 0x0, 0, 0x803C520A),
  "Spectacle Island - Barrel Shooting - First Prize": LocationData("Barrel Shooting - 1st Prize", EVENT, 0x0, 0, 0x803C52E3),
  "Spectacle Island - Barrel Shooting - Second Prize": LocationData("Barrel Shooting - 2nd Prize", EVENT, 0x0, 1, 0x803C52E3),
  "Needle Rock Isle - Chest": LocationData("Chest", CHEST, 0x0, 3),
  "Needle Rock Isle - Cave": LocationData("Cave", CHEST, 0xD, 9),
  "Needle Rock Isle - Golden Gunboat": LocationData("Golden Gunboat", BOCTO, 0x0, 2, 0x803C5202),
  "Angular Isles - Peak": LocationData("Peak", CHEST, 0x0, 0),
  "Angular Isles - Cave": LocationData("Cave", CHEST, 0xD, 6),
  "Boating Course - Raft": LocationData("Raft", CHEST, 0x0, 21),
  "Boating Course - Cave": LocationData("Cave", CHEST, 0xD, 15),
  "Stone Watcher Island - Cave": LocationData("Cave", CHEST, 0xC, 10),
  "Stone Watcher Island - Lookout Platform Chest": LocationData("Lookout Platform Chest", CHEST, 0x1, 18),
  "Stone Watcher Island - Lookout Platform - Destroy the Cannons": LocationData("Lookout - Cannons", CHEST, 0x0, 20),
  "Islet of Steel - Interior": LocationData("Interior", CHEST, 0xC, 4),
  "Islet of Steel - Lookout Platform - Defeat the Enemies": LocationData("Lookout - Enemies", CHEST, 0x1, 16),
  "Overlook Island - Cave": LocationData("Cave", CHEST, 0xC, 11),
  "Bird's Peak Rock - Cave": LocationData("Cave", CHEST, 0xC, 16),
  "Pawprint Isle - Chuchu Cave - Chest": LocationData("Chuchu Cave - Chest", CHEST, 0xC, 26),
  "Pawprint Isle - Chuchu Cave - Behind Left Boulder": LocationData("Chuchu Cave - Left Boulder", CHEST, 0xC, 24),
  "Pawprint Isle - Chuchu Cave - Behind Right Boulder": LocationData("Chuchu Cave - Right Boulder", CHEST, 0xC, 25),
  "Pawprint Isle - Chuchu Cave - Scale the Wall": LocationData("Chuchu Cave - Scale the Wall", CHEST, 0xC, 2),
  "Pawprint Isle - Wizzrobe Cave": LocationData("Wizzrobe Cave", CHEST, 0xD, 2),
  "Pawprint Isle - Lookout Platform - Defeat the Enemies": LocationData("Lookout - Enemies", CHEST, 0x1, 5),
  "Thorned Fairy Island - Great Fairy": LocationData("Great Fairy", EVENT, 0xC, 0, 0x803C525C),
  "Thorned Fairy Island - Northeastern Lookout Platform - Destroy the Cannons": LocationData("NE Lookout - Cannons", CHEST, 0x1, 14),
  "Thorned Fairy Island - Southwestern Lookout Platform - Defeat the Enemies": LocationData("SW Lookout - Enemies", CHEST, 0x1, 15),
  "Eastern Fairy Island - Great Fairy": LocationData("Great Fairy", EVENT, 0xC, 3, 0x803C525C),
  "Eastern Fairy Island - Lookout Platform - Defeat the Cannons and Enemies": LocationData("Lookout - Cannons, Enemies", CHEST, 0x1, 10),
  "Western Fairy Island - Great Fairy": LocationData("Great Fairy", EVENT, 0xC, 1, 0x803C525C),
  "Western Fairy Island - Lookout Platform": LocationData("Lookout Platform", CHEST, 0x1, 6),
  "Southern Fairy Island - Great Fairy": LocationData("Great Fairy", EVENT, 0xC, 2, 0x803C525C),
  "Southern Fairy Island - Lookout Platform - Destroy the Northwest Cannons": LocationData("Lookout - Northwest Cannons", CHEST, 0x0, 23),
  "Southern Fairy Island - Lookout Platform - Destroy the Southeast Cannons": LocationData("Lookout - Southeast Cannons", CHEST, 0x1, 17),
  "Northern Fairy Island - Great Fairy": LocationData("Great Fairy", EVENT, 0xC, 5, 0x803C525C),
  "Northern Fairy Island - Submarine": LocationData("Submarine", CHEST, 0xA, 6),
  "Tingle Island - Ankle - Reward for All Tingle Statues": LocationData("Ankle - All Tingle Statues", SPECL, 0x0, 0),
  "Tingle Island - Big Octo": LocationData("Big Octo", BOCTO, 0x0, 0, 0x803C51EA),
  "Diamond Steppe Island - Warp Maze Cave - First Chest": LocationData("Warp Maze Cave - First Chest", CHEST, 0xC, 23),
  "Diamond Steppe Island - Warp Maze Cave - Second Chest": LocationData("Warp Maze - Second Chest", CHEST, 0xC, 3),
  "Diamond Steppe Island - Big Octo": LocationData("Big Octo", BOCTO, 0x0, 0, 0x803C5210),
  "Bomb Island - Cave": LocationData("Cave", CHEST, 0xC, 5),
  "Bomb Island - Lookout Platform - Defeat the Enemies": LocationData("Lookout - Enemies", CHEST, 0x1, 3),
  "Bomb Island - Submarine": LocationData("Submarine", CHEST, 0xA, 2),
  "Rock Spire Isle - Cave": LocationData("Cave", CHEST, 0xC, 8),
  "Rock Spire Isle - Beedle's Special Shop Ship - 500 Rupee Item": LocationData("Special Shop - 500 Rupees", EVENT, 0xA, 5, 0x803C524C),
  "Rock Spire Isle - Beedle's Special Shop Ship - 950 Rupee Item": LocationData("Special Shop - 950 Rupees", EVENT, 0xA, 4, 0x803C524C),
  "Rock Spire Isle - Beedle's Special Shop Ship - 900 Rupee Item": LocationData("Special Shop - 900 Rupees", EVENT, 0xA, 3, 0x803C524C),
  "Rock Spire Isle - Western Lookout Platform - Destroy the Cannons": LocationData("W Lookout - Cannons", CHEST, 0x1, 23),
  "Rock Spire Isle - Eastern Lookout Platform - Destroy the Cannons": LocationData("E Lookout - Cannons", CHEST, 0x1, 24),
  "Rock Spire Isle - Center Lookout Platform": LocationData("Center Lookout Platform", CHEST, 0x1, 25),
  "Rock Spire Isle - Southeast Gunboat": LocationData("Southeast Gunboat", BOCTO, 0x0, 0, 0x803C51E8),
  "Shark Island - Cave": LocationData("Cave", CHEST, 0xD, 22),
  "Cliff Plateau Isles - Cave": LocationData("Cave", CHEST, 0xC, 7),
  "Cliff Plateau Isles - Highest Isle": LocationData("Highest Isle", CHEST, 0x0, 1),
  "Cliff Plateau Isles - Lookout Platform": LocationData("Lookout Platform", CHEST, 0x1, 19),
  "Crescent Moon Island - Chest": LocationData("Chest", CHEST, 0x0, 4),
  "Crescent Moon Island - Submarine": LocationData("Submarine", CHEST, 0xA, 7),
  "Horseshoe Island - Play Golf": LocationData("Play Golf", CHEST, 0x0, 5),
  "Horseshoe Island - Cave": LocationData("Cave", CHEST, 0xD, 1),
  "Horseshoe Island - Northwestern Lookout Platform": LocationData("NW Lookout", CHEST, 0x1, 26),
  "Horseshoe Island - Southeastern Lookout Platform": LocationData("SE Lookout", CHEST, 0x1, 27),
  "Flight Control Platform - Bird-Man Contest - First Prize": LocationData("Bird-Man Contest 1st Prize", EVENT, 0x0, 6, 0x803C5257),
  "Flight Control Platform - Submarine": LocationData("Submarine", CHEST, 0xA, 3),
  "Star Island - Cave": LocationData("Cave", CHEST, 0xC, 6),
  "Star Island - Lookout Platform": LocationData("Lookout Platform", CHEST, 0x1, 4),
  "Star Belt Archipelago - Lookout Platform": LocationData("Lookout Platform", CHEST, 0x1, 11),
  "Five-Star Isles - Lookout Platform - Destroy the Cannons": LocationData("Lookout - Cannons", CHEST, 0x1, 2),
  "Five-Star Isles - Raft": LocationData("Raft", CHEST, 0x0, 2),
  "Five-Star Isles - Submarine": LocationData("Submarine", CHEST, 0xA, 1),
  "Seven-Star Isles - Center Lookout Platform": LocationData("Center Lookout Platform", CHEST, 0x1, 8),
  "Seven-Star Isles - Northern Lookout Platform": LocationData("Northern Lookout Platform", CHEST, 0x1, 7),
  "Seven-Star Isles - Southern Lookout Platform": LocationData("Southern Lookout Platform", CHEST, 0x0, 22),
  "Seven-Star Isles - Big Octo": LocationData("Big Octo", BOCTO, 0x0, 0, 0x803C51D4),
  "Cyclops Reef - Destroy the Cannons and Gunboats": LocationData("Cannons and Gunboats", CHEST, 0x0, 11),
  "Cyclops Reef - Lookout Platform - Defeat the Enemies": LocationData("Lookout - Enemies", CHEST, 0x1, 12),
  "Two-Eye Reef - Destroy the Cannons and Gunboats": LocationData("Cannons and Gunboats", CHEST, 0x0, 13),
  "Two-Eye Reef - Lookout Platform": LocationData("Lookout Platform", CHEST, 0x1, 21),
  "Two-Eye Reef - Big Octo Great Fairy": LocationData("Big Octo Great Fairy", SWTCH, 0x0, 52),
  "Three-Eye Reef - Destroy the Cannons and Gunboats": LocationData("Cannons and Gunboats", CHEST, 0x0, 12),
  "Four-Eye Reef - Destroy the Cannons and Gunboats": LocationData("Cannons and Gunboats", CHEST, 0x0, 14),
  "Five-Eye Reef - Destroy the Cannons": LocationData("Destroy the Cannons", CHEST, 0x0, 15),
  "Five-Eye Reef - Lookout Platform": LocationData("Lookout Platform", CHEST, 0x1, 20),
  "Six-Eye Reef - Destroy the Cannons and Gunboats": LocationData("Cannons and Gunboats", CHEST, 0x0, 17),
  "Six-Eye Reef - Lookout Platform - Destroy the Cannons": LocationData("Lookout - Cannons", CHEST, 0x1, 13),
  "Six-Eye Reef - Submarine": LocationData("Submarine", CHEST, 0xA, 0),
  "Forsaken Fortress Sector - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 8),
  "Star Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 18),
  "Northern Fairy Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 51),
  "Gale Isle - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 33),
  "Crescent Moon Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 40),
  "Seven-Star Isles - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 38),
  "Overlook Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 15),
  "Four-Eye Reef - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 12),
  "Mother and Child Isles - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 56),
  "Spectacle Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 5),
  "Windfall Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 58),
  "Pawprint Isle - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 42),
  "Dragon Roost Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 50),
  "Flight Control Platform - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 13),
  "Western Fairy Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 10),
  "Rock Spire Isle - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 48),
  "Tingle Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 0),
  "Northern Triangle Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 11),
  "Eastern Fairy Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 62),
  "Fire Mountain - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 9),
  "Star Belt Archipelago - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 17),
  "Three-Eye Reef - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 49),
  "Greatfish Isle - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 32),
  "Cyclops Reef - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 16),
  "Six-Eye Reef - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 52),
  "Tower of the Gods Sector - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 1),
  "Eastern Triangle Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 57),
  "Thorned Fairy Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 44),
  "Needle Rock Isle - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 60),
  "Islet of Steel - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 54),
  "Stone Watcher Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 34),
  "Southern Triangle Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 37),
  "Private Oasis - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 55),
  "Bomb Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 43),
  "Bird's Peak Rock - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 6),
  "Diamond Steppe Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 45),
  "Five-Eye Reef - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 53),
  "Shark Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 59),
  "Southern Fairy Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 61),
  "Ice Ring Isle - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 7),
  "Forest Haven - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 46),
  "Cliff Plateau Isles - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 36),
  "Horseshoe Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 4),
  "Outset Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 35),
  "Headstone Island - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 63),
  "Two-Eye Reef - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 39),
  "Angular Isles - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 41),
  "Boating Course - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 14),
  "Five-Star Isles - Sunken Treasure": LocationData("Sunken Treasure", CHART, 0x0, 47),
}
